services:
  db:
    container_name: postgresql_container
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./datadb:/var/lib/postgresql/data
    restart:
      always
  backend:
    build: .
    container_name: app_con
    ports:
      - 8090:8090
    depends_on:
      - db
    restart: always


